# Generated by Django 5.0.1 on 2024-02-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_orderitem_coupon_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
